export const FETCH_CONCERTS = 'FETCH_CONCERTS';
export const FETCH_CONCERTS_SUCCESS = 'FETCH_CONCERTS_SUCCESS';
export const FETCH_CONCERTS_FAIL = 'FETCH_CONCERTS_FAIL';

export const FETCH_CONCERT = 'FETCH_CONCERT';
export const FETCH_CONCERT_SUCCESS = 'FETCH_CONCERT_SUCCESS';
export const FETCH_CONCERT_FAIL = 'FETCH_CONCERT_FAIL';