export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_START = 'DELETE_REVIEW_START';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED';