jobs: 
  build: 
    working_directory: ~/podkowczers
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
      - image: postgres:9.5
        environment:
          POSTGRES_DB: podkowczers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout:
          path: ~/podkowczers/backend
      - run: sudo gem update --system
      - run: sudo gem install bundler:2.0.2
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Check directory
          command: sh -c ls
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:setup --trace
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results