jobs: 
  build: 
    working_directory: ~/podkowczers
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
      - image: postgres:9.5
        environment:
          POSTGRES_DB: podkowczers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - run: sudo gem update --system
      - run: sudo gem install bundler:2.0.2
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
        name: Which folder?
        command: pwd
      - run:
        name: Dirs?
        command: ls
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: cd ./backend && bin/rails db:setup --trace
      - run: |
          cd ./backend && bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results