jobs: 
  build: 
    working_directory: ~/podkowczers/backend
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
          REDIS_URL: redis://redis:6379/12
          TICKETS_SECRET: f28ff3ec154055ab2c73f189af61e9bf12159836efc34f2e01bece85d66911ca 
          PGHOST: localhost
          PGUSER: postgres
      - image: circleci/redis:rc-alpine3.11
      - image: postgres:9.5
        environment:
          POSTGRES_DB: podkowczers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout:
          path: ~/podkowczers
      - run: sudo gem update --system
      - run: sudo gem install bundler:2.0.2
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:setup --trace
      - run: |
              bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results