version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build
      - upload_coverage:
          requires:
            - build
      - deploy:
          requires:
            - build
jobs:
  build:
    working_directory: ~/podkowczers/backend
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
          TICKETS_SECRET: f28ff3ec154055ab2c73f189af61e9bf
          PGHOST: localhost
          PGUSER: postgres
      - image: redis
      - image: postgres:9.5
        environment:
          POSTGRES_DB: podkowczers
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - checkout:
          path: ~/podkowczers
      - run:
          name: Setup dependencies
          command: |
            sudo composer self-update
            composer install -n --prefer-dist
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
      - run:
          name: 'Get dependencies'
          command: |
            sudo apt-get install -y wget xfonts-utils && \
            sudo wget http://mirrors.kernel.org/ubuntu/pool/main/x/xfonts-utils/xfonts-utils_7.7+3_amd64.deb -P /var/www/downloads && \
            sudo dpkg -i /var/www/downloads/xfonts-utils_7.7+3_amd64.deb && \
            sudo wget http://mirrors.kernel.org/ubuntu/pool/main/x/xfonts-base/xfonts-base_1.0.4+nmu1_all.deb -P /var/www/downloads && \
            sudo dpkg -i /var/www/downloads/xfonts-base_1.0.4+nmu1_all.deb && \
            sudo wget http://mirrors.kernel.org/ubuntu/pool/universe/x/xfonts-75dpi/xfonts-75dpi_1.0.4+nmu1_all.deb -P /var/www/downloads && \
            sudo dpkg -i /var/www/downloads/xfonts-75dpi_1.0.4+nmu1_all.deb && \
            sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb -P /var/www && \
            sudo dpkg -i  /var/www/wkhtmltox_0.12.5-1.stretch_amd64.deb
      - run: sudo gem update --system
      - run: sudo gem install bundler:2.0.2
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 2m
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:create --trace && bin/rails db:migrate --trace
      - run:
          name: Run backend tests
          command: |
            bundle exec rake
            ./tmp/cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.backend.json coverage/backend/.resultset.json
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.backend.json
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: coverage
  upload-coverage:
    working_directory: ~/podkowczers/backend
    docker:
      - image: circleci/ruby:2.4.2-jessie-node-browsers
    environment:
      - CC_TEST_REPORTER_ID: b73d0b37c132d1b5d5d4a98998249a549e77b924f78ecc79e6605453dd44cabc
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
  deploy:
    docker:
      - image: circleci/golang:1.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d0:70:0e:26:ef:95:63:bc:29:e7:22:ee:11:ed:c1:f8"
      - run: |
          ssh -oStrictHostKeyChecking=no podkowczers@51.178.16.104 \<<'ENDSSH'
          cd ./app/podkowczers && bash deploy.sh
          ENDSSH