export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';

export const FETCH_EVENT = 'FETCH_EVENT';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAIL = 'FETCH_EVENT_FAIL';

export const BOOK_TICKETS = 'BOOK_TICKETS';
export const BOOK_TICKETS_SUCCESS = 'BOOK_TICKETS_SUCCESS';
export const BOOK_TICKETS_FAIL = 'BOOK_TICKETS_FAIL';