version: "3.4"
services:
  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/
    env_file:
      - ../../.env.prod
  redis:
    image: redis:latest
    volumes:
      - /var/lib/redis/data
  sidekiq:
    build:
      dockerfile: Dockerfile
      context: ../../backend
    command: "bundle exec sidekiq -q default -q user_tickets "
    volumes:
      - ../../backend:/api
    env_file:
      - ../../.env.prod
    depends_on:
      - redis
  api:
    build:
      dockerfile: Dockerfile
      context: ../../backend
    env_file:
      - ../../.env.prod
    command: sh -c "rails db:create && rails db:migrate && rails s -p 4000 -b 0.0.0.0"
    volumes:
      - ../../backend:/api
    ports:
      - 4000:4000
    depends_on:
      - db
  client:
    build:
      dockerfile: Dockerfile
      context: ../../frontend
    env_file:
      - ../../.env.prod
    volumes:
      - ../../frontend:/app
    depends_on:
      - api
