version: "3.4"
services:
  db:
    image: postgres:latest
    volumes:
      - ../../postgres-data:/var/lib/postgresql/data
    env_file:
      - ../../.env.prod
  redis:
    image: redis:latest
    volumes:
      - ../../redis-data:/var/lib/redis/data
  sidekiq:
    build:
      dockerfile: Dockerfile
      context: ../../backend
    command: sh -c "bundle install && bundle exec sidekiq -q default -q user_tickets "
    volumes:
      - ../../backend:/api
    env_file:
      - ../../.env.prod
    depends_on:
      - redis
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  api:
    build:
      dockerfile: Dockerfile
      context: ../../backend
    environment:
      - VIRTUAL_HOST=api.depodkowczers.walbrzych.pl
    env_file:
      - ../../.env.prod
    command: sh -c "bundle install && whenever --update-crontab && rails db:create && rails db:migrate && rm -f /api/tmp/pids/server.pid && rails s -p 4000 -b 0.0.0.0"
    volumes:
      - ../../backend:/api
    ports:
      - 4000:4000
    depends_on:
      - db
  web:
    build:
      dockerfile: Dockerfile
      context: ../../frontend
    environment:
      - VIRTUAL_HOST=depodkowczers.walbrzych.pl
    env_file:
      - ../../.env.prod
    ports:
      - 8080:8080
    depends_on:
      - db
      - api