export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const ADD_COIN = 'ADD_COIN';
export const ADD_COIN_START = 'ADD_COIN_START';
export const ADD_COIN_SUCCESS = 'ADD_COIN_SUCCESS';
export const ADD_COIN_FAILED = 'ADD_COIN_FAILED';

export const CHANGE_ROLE = 'CHANGE_ROLE';
export const CHANGE_ROLE_START = 'CHANGE_ROLE_START';
export const CHANGE_ROLE_SUCCESS = 'CHANGE_ROLE_SUCCESS';
export const CHANGE_ROLE_FAILED = 'CHANGE_ROLE_FAILED';