export const DELETE_TICKET = 'DELETE_TICKET';
export const DELETE_TICKET_START = 'DELETE_TICKET_START';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAILED = 'DELETE_TICKET_FAILED';