export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const FETCH_USER = 'FETCH_USER';
export const FILL_PROFILE = 'FILL_PROFILE';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const MAKE_RESERVATION = 'MAKE_RESERVATION';
export const RESERVATION_SUCCESS = 'RESERVATION_SUCCESS';
export const RESERVATION_FAILED = 'RESERVATION_FAILED';

export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';